report:
	export AMPY_PORT=/dev/ttyUSB0
	ampy run report.py

test:
	ampy run main.py
	
publish:
	# ../webrepl/webrepl_cli.py -p $$SECRET ~/git/minions/esp8266/strip/main.py 192.168.1.117:
	# ../webrepl/webrepl_cli.py -p $$SECRET ~/git/minions/esp8266/strip/main.py 192.168.1.118:
	../webrepl/webrepl_cli.py -p $$SECRET ~/git/minions/esp8266/strip/main.py 192.168.1.116:
	#../webrepl/webrepl_cli.py -p $$SECRET ~/git/minions/esp8266/strip/main.py 192.168.1.103:
	../webrepl/webrepl_cli.py -p $$SECRET ~/git/minions/esp8266/strip/main.py 192.168.1.119:
	#../webrepl/webrepl_cli.py -p $$SECRET ~/git/minions/esp8266/strip/main.py 192.168.1.149:
	#../webrepl/webrepl_cli.py -p $$SECRET ~/git/minions/esp8266/strip/main.py 192.168.1.124:
	../webrepl/webrepl_cli.py -p $$SECRET ~/git/minions/esp8266/strip/main.py 192.168.1.111: